name: Deploy to github pages

on:
  push:
    branches: [ignore-all]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.101
          # publishes Blazor project to the release-folder

      - name: Publish .NET Core Project
        run: dotnet publish ./src/BlazorDatasheet.Wasm/BlazorDatasheet.Wasm.csproj -c Release -o release --nologo

      - name: Change base-tag in index.html from / to BlazorDatasheet
        run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorDatasheet\/" \/>/g' release/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
